### PR TITLE
add grunt task to check filesizes when deploying

### PR DESCRIPTION
**Pull request by akash1810**
this will check that:
- any new video is < 1MB
- any new image is < 200kb
- you're not using gifs!

and will fail the grunt task if you exceed the limits

img

### CODE REVIEW

**Comment by LisaVillani** [comment]
1mb is quite a lot of leeway on the vids!

**Comment by sndrs** [comment]
@LisaVillani do you think it's too much?

**Comment by LisaVillani** [comment]
Well I am trying to keep the thrasher vids below 750mb but it depends on what it's for I suppose. I will do my best to keep the clips short, under 750kb and will optimise those bg images too!

**Comment by akash1810** [comment]
It's worth noting the limits here have been set on assumptions and past thrashers, they're reasonable assumptions though imo. If we're unable to meet the limits, maybe we should consider using YouTube or different encodings such as HLS or DASH to get adaptive streaming?

**Comment by duarte** [comment]
There's an `empty.gif` image used often to load JS in thrashers. I think it's over 1 byte — I wonder if this will be a problem? Maybe we could add a new, smaller empty.gif image as part of this PR to the new thrasher template?

**Comment by akash1810** [comment]
> There's an empty.gif image used often to load JS in thrashers. I think it's over 1 byte — I wonder if this will be a problem?

Good point. Judging by [this gif](https://github.com/guardian/thrashers/blob/master/embeds/the-flyer/_source/empty.gif), I'd suggest we bump the limit to 1.5kb, which should be more than enough.

> Maybe we could add a new, smaller empty.gif image as part of this PR to the new thrasher template?

I think this would be out of the scope for this PR. But does sound like a good thing to do!

**Pull request merged**
