### PR TITLE
Membership bundles AB test thrasher

### PR DESCRIPTION
**Pull request by JustinPinner**
We're about to begin a 404 AB test for membership bundles, and we need a thrasher to behave like the wardrobe door to Narnia.

It'll attract vast* numbers of readers through to one of two flavours of membership landing pages, from where they'll be so excited by the things they can buy, they'll be fighting to hand over their honest, hard-earned cash to us. But they won't be able to because this is a 404 test.

The plan is simple: We've defined the thrasher so that if the AB test or my CSS acts screwy for any unforeseen reason, it'll still provide a working route to the existing supporter sign-up page. That's our backstop in the event of much weirdness.

However, when the CSS (added to facia) works the thrasher will be hidden by default. Then if the test is enabled and the user is partitioned into one of the cohorts, the test makes the thrasher visible and modifies the text and button link target which, if clicked, moves them on to one of our new landing pages.

(image updated 26 Jan)
screen shot 2017-01-26 at 12 16 33

Thanks!

*Hundreds of thousands. Trust me, I'm a big fan of readers. I've got awards in readers. They love this. They told me.

### CODE REVIEW

**Comment by superfrank** [comment]
Is there a designer as part of your team @JustinPinner ? If not, it may be worth showing this to Ben Weursching as he was a designer on Members for quite a while so may have some thoughts/feelings on the design. 

Initial questions/thoughts: What's the page this'll link to? As the thrasher should try and represent that with it's colour choices/branding. Where will this thrasher sit? As a general rule of thumb we try to keep them down to about 280px in height (unless it's at the bottom of a front) as otherwise it's a little overwhelming.

**Comment by JustinPinner** [comment]
Hi @superfrank, Ben W is our designer. He even gave us this crazy green scheme and dimensions. The thrasher is planned to go as high up the page as possible, but it will only be seen by 5% of UK desktop browsers who are running a minimum 1140px wide breakpoint. Overwhelming is kind of what we're looking for!

**Comment by JustinPinner** [comment]
Also, it leads to pages that look like this: https://membership.theguardian.com/bundles?intcmp=MEMBERSHIP_AB_THRASHER_UK_B1

**Comment by superfrank** [comment]
👍 Cool, already one step ahead. 

I'd keep the padding on the arrow on the Thrasher CTA consistent with the ones on the page: 
image 

and look into maybe pulling in the membership branding in the top right. Similar to the way the G is placed top right here (but double check this with Ben):
image

but otherwise all good.

**Comment by JustinPinner** [comment]
I'll ask about the padding on the button, but Ben specifically asked me to remove the branding (I'd originally left it there from the thrasher I copied it all from in the first place).

Thanks for the comments though. What's involved in getting this into production once it's merged?

**Comment by superfrank** [comment]
You'll need to pass the snap path onto someone like Central Production/someone with access to creating containers on the fronts.

My main editorial contact for that stuff is usually Celine, but guess it'll be different for your team.

**Comment by JustinPinner** [comment]
How do I get an actual 👍 for this PR? Do I need one before merging back to master?

**Comment by rtyley** [comment]
> How do I get an actual :+1:  for this PR? Do I need one before merging back to master?

The file changes are all restricted to the new `embeds/membership-ab-thrasher` folder - ie they can't break anyone else's thrasher - so I don't think you need 'authorisation' to merge the changes here, at most, you just want to feel comfortable that they will work. The thrasher can always be rapidly removed if it breaks something on DotCom frontend!

**Comment by JustinPinner** [comment]
Agreed. Didn't know if they followed the same process as frontend and us though.

**Comment by superfrank** [comment]
As you can get the Thrasher live without merging it we're generally a bit (a lot) more slack. As there's normally a deadline with this kind of thing. I guess it's generally good practice to get a quick look over and a thumbs up when merging afterwards though, but yeh don't feel you have to hold it back.

👍

**Comment by JustinPinner** [comment]
Thanks Frank. Merging now.

**Comment by sammorrisdesign** [comment]
What @superfrank said

**Comment by JustinPinner** [comment]
Cheers, @sammorrisdesign 🏁

**Pull request merged**
